$.noConflict();
jQuery(document).ready(function($){
    $("#play").click(function(){
        playMusic();
    });
    $("#pause").click(function(){
        playMusic();
    });
    $(window).resize(function(){
        setSize();
    });
});